version: 0.1

phases:
  install:
    commands:
      - pip install virtualenv
  pre_build:
    commands:
      - mkdir venv
      - virtualenv --python=python2.7 venv/lambda
      - which python
      - source venv/lambda/bin/activate
      - echo $VIRTUAL_ENV
      - which python
      - deactivate
